// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0V4LOzvCqfKofSfY8jHlzsWVq2MJn2yc',
    appId: '1:740953369648:web:fb46100331c2f5e9cc51f5',
    messagingSenderId: '740953369648',
    projectId: 'glucare-app',
    authDomain: 'glucare-app.firebaseapp.com',
    storageBucket: 'glucare-app.firebasestorage.app',
    measurementId: 'G-CKHQ12SMEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOP2YAk7WVVmv5lhcNfN0A_mday9E1iro',
    appId: '1:740953369648:android:cbb8611ad7f3f1a1cc51f5',
    messagingSenderId: '740953369648',
    projectId: 'glucare-app',
    storageBucket: 'glucare-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSZw3e1aQkM1O1dq6TWhwFLUIh0I1jwqk',
    appId: '1:740953369648:ios:eca02c42484e30e5cc51f5',
    messagingSenderId: '740953369648',
    projectId: 'glucare-app',
    storageBucket: 'glucare-app.firebasestorage.app',
    iosBundleId: 'com.example.glucareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSZw3e1aQkM1O1dq6TWhwFLUIh0I1jwqk',
    appId: '1:740953369648:ios:eca02c42484e30e5cc51f5',
    messagingSenderId: '740953369648',
    projectId: 'glucare-app',
    storageBucket: 'glucare-app.firebasestorage.app',
    iosBundleId: 'com.example.glucareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0V4LOzvCqfKofSfY8jHlzsWVq2MJn2yc',
    appId: '1:740953369648:web:c62328a44fa2ac8ecc51f5',
    messagingSenderId: '740953369648',
    projectId: 'glucare-app',
    authDomain: 'glucare-app.firebaseapp.com',
    storageBucket: 'glucare-app.firebasestorage.app',
    measurementId: 'G-QSYFHL00BQ',
  );

}